### ISSUE TITLE
Unknown type `ktn_code:tree_node/0`

### ISSUE THREAD

**Issue by NobbZ** [inaka/katana-code#27]
In a project of mine I have enabled `unknown` warnings and see the warning mentioned in the subject.

As `tree_node/0` and `tree_node_type/0` are both used in typespecs as input and return values, they should probably be exported via `-export_type(…)` where `…` is a list, similar to how `-export(…)` looks like.

**Comment by elbrujohalcon** [comment]
Thanks, @NobbZ

**Comment by elbrujohalcon** [comment]
This change is included in release 0.1.3 now :)
