### ISSUE TITLE
Published documentation on hexdocs.pm contains private functions

### ISSUE THREAD

**Issue by NobbZ** [inaka/katana-code#30]
The documentation pushed to hexdocs.pm (https://hexdocs.pm/katana_code/) lists private functions.

Could the documentation perhaps rebuilt with `{hidden, false}, {private, false}` and republished and in future the release process hide non public functions per default?

**Comment by elbrujohalcon** [comment]
I think that's a great idea. Do you mind sending us a PR with the required changes to rebar.config?
I can take care of the publishing afterwards.
