### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/katana-code#77]
The latest `main` code, namely the one that doesn't force `{feature, maybe_expr, enable}` on consumers, could do with a release.

`katana_code` is, at least, used in `rebar3_hank`, `rebar3_format`, and `elvis_core`, which depend (circularly) amongst themselves.

`elvis_core`:
* katana_code
* rebar3_format (depends on rebar3_lint, which depends on this)
* rebar3_hank (depends on rebar3_lint, which depends on this)

`rebar3_format`:
* katana_code
* rebar3_lint (depends on elvis_core, which depends on this)
* rebar3_hank (depends on this)

`rebar3_hank`:
* katana_code
* rebar3_lint (depends on elvis_core, which depends on this)
* rebar3_format (depends on this)

`rebar3_lint`:
* elvis_core
* rebar3_hank (depends on this)

😄

**Comment by paulo-ferraz-oliveira** [comment]
FYI @elbrujohalcon

**Comment by elbrujohalcon** [comment]
Done. https://hex.pm/packages/katana_code/2.0.2

**Comment by paulo-ferraz-oliveira** [comment]
Cool, thanks. I'll get on the "linked" pull requests.
