### ISSUE TITLE
Cannot handle map comprehensions introduced in OTP-26

### ISSUE THREAD

**Issue by sile** [inaka/katana-code#78]
## Bug Description

If source code contains map comprehensions, `rebar3_lint` returns `unhandled_abstract_form` error (at [katana-code/src/ktn_code.erl#728](https://github.com/inaka/katana-code/blob/689d81dc1a29776288b14c8226adc1bf7b252c0a/src/ktn_code.erl#L728)).

## To Reproduce

```console
$ rebar3 new --lib foo
$ cd foo
$ echo '{project_plugins, [rebar3_lint]}.' >> rebar.config
$ $EDITOR src/foo.erl
-module(foo).
-export([foo/0]).

foo() ->
    Map = #{},
    [ K || K := _ <- Map ],

    List = [],
    #{ X => ok || X <- List },

    ok.

$ rebar3 lint
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling foo
===> elvis analysis starting, this may take a while...
Error: {unhandled_abstract_form,
                           {m_generate,
                               [{text,"<-"},{location,{8,19}}],
                               {map_field_exact,
                                   [{text,":="},{location,{8,14}}],
                                   {var,[{text,"K"},{location,{8,12}}],'K'},
                                   {var,[{text,"_"},{location,{8,17}}],'_'}},
                               {var,[{text,"Map"},{location,{8,22}}],'Map'}}} when loading file "src/foo.erl".
Warning: Searching for files in ["."], for ruleset elvis_config, with filter "elvis.config", yielded none. Update your configuration.
```

## Expected Behavior
`rebar3_lint` succeeds without errors.

## `rebar3` Logs
[rebar3.log](https://github.com/inaka/katana-code/files/12236200/rebar3.log)

## Additional Context
 - OS: MacOS
 - Erlang version: OTP 26.0
 - rebar3 version: 3.18.0

**Comment by elbrujohalcon** [comment]
Good catch, @sile! I wonder if @pablocostass or any other of the map-comprehension implementors would have some spare time to generate a PR for this here. 🙏🏻

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I just saw this now. I was updating some other stuff for this lib. and since the tests didn't run in OTP 26 I started handling it.

**Comment by sile** [comment]
Thank you for your quick fix!

**Comment by sile** [comment]
The latest version of `rebar3_lint` was able to handle my code, including map comprehensions. Perfect!
